POST http://localhost:9393/tabungan
Content-Type: application/json

{
    "tabungan_harian": 20000
}


POST http://localhost:9393/tabungan
Content-Type: application/json

{
  "tabungan_harian": 40000
}

GET http://localhost:9393/tabungans
Content-Type: application/json


DELETE http://localhost:9393/delete-tabungan?id=1
Content-Type: application/json